runs:

  using: 'composite'

  steps:

  - name: Install Linux dependencies
    shell: bash
    if: runner.os == 'Linux'
    run: |
      sudo apt-get update -yq
      sudo apt-get install -yq --no-install-recommends zlib1g-dev lib${{ matrix.mpi }}-dev

  - name: Install macOS dependencies
    shell: bash
    if: runner.os == 'macOS'
    run: brew install open-mpi
